main-system: 'org.melusina.github-actions'
unit-tests:
  system: 'org.melusina.github-actions/testsuite'
  entrypoint: 'unit-tests'
#component-tests:
#deployment-tests:
linter:
  system: 'org.melusina.github-actions/development'
  entrypoint: 'lint'

fast:
  os:
    - ubuntu-latest
  implementation:
    - sbcl
tier-1:
  os:
    - ubuntu-latest
    - macos-latest
  implementation:
    - sbcl
tier-2:
  os:
    - ubuntu-latest
    - macos-latest
  implementation:
    - abcl
    - ccl
    - clisp
    - ecl
    - gcl
